import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Sidebar.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='flex w-full h-full flex-row'>
      <body className='flex w-full h-full flex-row'>
        {" "}
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
