import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Sidebar.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='flex w-full flex-row'>
      <body className='flex w-full flex-row'>
        {" "}
        <Sidebar className='flex w-full sticky top-0' />
        <div className='flex-1 overflow-y-auto'>
          {children}
        </div>
      </body>
    </html>
  );
}
